// Pre-parsed gratitude notes from assets/list.rtf
// These are imported with unknown dates (null) - users can add dates later

export const seedNotes: string[] = [
  "the smell of your favourite coffee in the morning",
  "hot showers on cold mornings with clean and cozy clothes afterwards",
  "Watch the rain and the rainbow afterwards",
  "Cuddles with your favourite stuffed animals",
  "Enjoy your favourite soup on a cold and rainy day",
  "To watch that movie your friend recommended on a rainy night",
  "To see snow",
  "To wear cozy socks and slippers in a cold day",
  "To treat yourself to a small gift",
  "To experience a day that you feel really really pretty and beautiful",
  "Getting hooked up on a new tv show",
  "To sleep with your favourite teddy bear",
  "To try out a new hobby",
  "To receive or get yourself your favourite flowers",
  "Spontaneous night drives for yummy food",
  "Receiving card or letters from people that loves you",
  "To watch a movie in the outdoor cinema while it's raining",
  "To read new books that you find very interesting",
  "To take yourself out for a warm coffee or tea",
  "Make a birthday wish",
  "To put candles in your room and make it cozy",
  "Travel one day somewhere you really want to visit",
  "To bake yummy treats for your friends and for yourself",
  "That feeling that it's like a rewind when you lay on the cold side of the pillow",
  "Late night drives with your favourite music playing on the car",
  "Morning walks in the winter sun",
  "To spend the day with a friend",
  "To look back to old photos with the best memories that have been created",
  "To have a little boogie to your favourite song",
  "To experience the 'butterflies'",
  "To achieve a recovery goal",
  "To taste new weird mixes of foods that actually taste good",
  "Bubble baths",
  "Cozy clothes",
  "To spend a day in bed watching movies",
  "To dye your hair fun and different colours",
  "The satisfying feeling of peeling the plastic off of something new",
  "The little joy you feel when you pop bubble wrap",
  "The comforting feeling of having your hair brushed by someone that you love",
  "To lick the spatula when you've finished baking",
  "Getting that excitement when something you have ordered a long time ago finally arrives",
  "Feeling the freedom of eating something you want",
  "For a home cooked meal (made with love from someone that loves you a lot)",
  "when the weather gets cold and you add in your bedding a blanket",
  "To put up clean bedding",
  "To be surprised with a present",
  "To have a good hair and make up day",
  "To watch a play in the theatre",
  "To go to fun events",
  "To taste your own baking",
  "To watch horror movies in the dark with friends and getting jump scares at every scary scene",
  "To smell different candles in a shop",
  "To join a class and learn something new",
  "To flip a pancake perfectly",
  "The feeling of getting in to fresh sheets after a shower",
  "To enjoy your morning with a cup of coffee and a beautiful view out of a window",
  "To feel at peace outside",
  "To feel that cold refreshing air outside while wearing very warm clothes",
  "To see your favourite animal",
  "For the sound of a cracking fire",
  "To discover new and aesthetically pleasing ditches",
  "Listen with headphones your favourite music in the bus",
  "Have an unforgettable moment around the fire with your friends",
  "To feed and pet some stray animals and farmyard animals",
  "Eating your favourite snack at the cinema",
  "To enjoy your childhood favourite snack",
  "For happy doggie kisses",
  "The feeling of waking up and realising you have more time to sleep",
  "The smell of your favourite perfume",
  "For FaceTime calls with your friends",
  "Cuddling with a pet",
  "To truly laugh when having fun",
  "To go to a theme park",
  "To watch Christmas movies after a long time with a hot chocolate or fast food and a blanket",
  "The smell of the fresh rain",
  "Late night ice cream",
  "Having your first salary",
  "Putting new clothes",
  "To wear your favourite shoes",
  "To learn something new about yourself",
  "Decorating the Christmas tree with Christmas songs",
  "To paint your nails with fun patterns",
  "To fix an object you thought it was broken",
  "Fun phone calls with your friends",
  "To pack up a suitcase ready for a trip",
  "For nights in hotels",
  "Go on an airplane for the first time / after a long time",
  "To dance in the rain alone or with someone you really love",
  "Feeling nostalgic of watching kids shows you used to watch as a kid",
  "Watching the sunset",
  "Pizza and movie nights",
  "Making new friends that genuinely care about you",
  "road trips",
  "Roof top mornings or nights",
  "Watching the stars",
  "Feeling proud of making someone laugh",
  "Laughing with your friends in class",
  "Feeling proud of achieving what you wanted",
  "That shock that you get after an unexpected plot twist from a good movie",
  "Getting wet in the rain without worrying",
  "Getting new earrings",
  "Smelling shampoos at the supermarket",
  "Tasting new ice cream flavours",
  "Eating your favourite junk food",
  "Listening for the first time songs that hits different",
  "Watching the moon",
  "Succeeding at making a new outfit in your mind and turning out good when you try it",
  "New songs from the artist you like",
  "Dancing alone in your room",
  "Making surprise parties for your friends",
  "Getting a new haircut that suits you a lot",
  "Finding out secret talents that you have",
  "putting water in dry rocks at the beach",
  "To open a can and count the letters until the metallic part comes off",
  "The smell of popcorn in a movie theatre",
  "The excitement you get when you're in the cinema and the lights turn off slowly when the movie is about to start",
  "Seeing the sun rise and set",
  "When you see your food coming in a restaurant",
  "Watching the stars with your loved ones",
  "Going to bed knowing you can sleep for as long as you want",
  "City lights at night",
  "Getting a compliment from a stranger",
  "Making a baby laugh",
  "The smell of fresh baked bread",
  "When you and a friend say the same thing at the same time",
  "Finding money in a pocket of a cloth you haven't worn in a while",
  "When someone remembers the things you like",
  "Going through the photos you took at the end of the day",
  "Getting lost in a book",
  "Smelling and touching the warm clothes after the dry machine finished",
  "Sleeping in the morning while every position is comfy",
  "Taking hot showers after a hard day",
  "Sunday's day care",
  "Entering a warm place after being in the cold weather and freezing",
  "Unboxing a thing you wanted to buy for such a long time",
  "Walking up in excitement about a trip you've been waiting for a long time",
  "Remembering funny and happy memories",
  "Finding the perfect song for the perfect moment",
  "Receiving a long detailed message on your birthday from someone you love",
  "Walking early in the morning while there are no people around",
  "Watch the snow after a long time",
  "Wearing funny and cute socks",
  "Watching a movie and finding one character that you relate so much that you feel not alone anymore",
  "Finding someone that listens to the same artists like you and getting excited about it",
  "Finding new hairstyles that suits you a lot",
  "Getting good grades after studying a lot and knowing that it was worth the studying",
  "Wearing your favourite scarf and smelling it and the softness of it hugging all your neck",
  "Cleaning your room with your favourite playlist",
  "Playing board games with your family or friends",
  "Listening to a new song knowing that it's going to be your favourite song for a while",
  "Going through an album of old pictures from the older generation",
  "Learning how to crochet",
  "Counting backwards for the new year that is coming",
  "Eating refreshing fruits in the summer after a hot day",
  "Beach times",
  "Watching the 'smoke' coming out of your mouth in the cold and just playing with it",
  "Creating a house with pillows and blankets",
  "Hearing your voice sounding weird in front of the fan",
  "Making a telescope with the hard piece of the paper roll or shouting into it like it's a megaphone",
  "Folding random things or paper because you're bored",
  "Watching yourself in the camera of a supermarket when you enter",
  "Waking with someone and the last person who's left behind is the loser",
  "Playing chase with someone",
  "Drawing things in the frosted car window",
  "Turning off the lights and running upstairs like someone is in the dark",
  "Watching the 'raindrop race' in the car",
  "licking the spoon after baking",
  "Creating and pop bubbles",
  "When you blow the candles of your birthday cake",
  "When you blow that one white flower and now it's all over the sky",
  "Playing with water guns in the summer",
  "Creating castles in the beach with sand",
  "Getting hurt and wearing funny bandaids",
  "Playing with the hula hoop",
  "walking in brand new soft shoes and feeling like walking in clouds",
  "Getting in the airplane for the first time",
  "Going to the car wash and being inside the car while washing",
  "Feeling the chilly breeze air while riding a bike",
  "Riding a bike freely in nature",
  "Drinking water after wanting it for a while",
  "Eating something sweet or drinking something while laughing with your friends in a cafeteria while it's raining",
  "Running with your friends in the rain because you're freezing",
  "Countdown for the new year with your loved ones",
  "Going to your favourite amusement park ride with your friends after a lot of time",
  "Secret Santa gifts",
  "Watching you did great for a test you put the effort for",
  "Watching your pet sleeping peacefully",
  "Watching an animal trusting you to pet him",
  "When someone you love prepares for you snacks or fruits while you are studying",
  "When someone you love peels the skin of the fruits you love",
  "When someone you love opens the water bottle for you without you asking for it",
  "The food you ordered is so delicious like you hoped it would be",
  "When the food tastes as much good as it smells",
  "When you eat your favourite food after a very long time",
  "Getting 'happy birthday' wishes from your loved ones",
  "Watching a good series that has gotten your attention so much",
  "Finishing a hard assignment",
  "seeing sunlight shine through tree leaves",
  "hearing your favourite song live at a concert",
  "going through an old box full of childhood things",
  "hearing someone snort when they laugh",
  "Seeing your breath on cold days",
  "when you laugh so hard no noise comes out",
  "when a person doesn't let go from a hug even after you do",
  "the sound of your footsteps in the snow",
  "Getting accepted into the university you studied hard for",
  "Moving abroad and starting a new life",
  "Meeting people from different cultures",
  "Exploring new parks full of beauty",
  "The excitement you get when you're about to scare/surprise someone successfully and then you laugh it out",
  "When your hair blows in the wind",
  "When it's so cold that your breath is visible",
  "The warmness of a restaurant when walking for a long time in the wind",
  "To feel loved and appreciated",
  "Dive into your adult years with the friends you love so much",
  "The privilege of being able to say that I can return home after a long day",
  "The privilege of returning in your home country and see your lovely family after being away for a long time",
  "The feeling of exchanging merry Christmas and happy new year wishes",
  "Having the privilege of still being able to taste food from your mother and grandmother",
  "Getting to know what being in love feels like",
  "Making eye contact with someone you really like",
  "Getting a love letter",
  "Helping someone and feeling good about it",
  "Finding a great new perfume",
  "Hugs that smell amazing",
  "Passing that exam you thought you would fail",
  "Singing with your friends",
  "Dancing with your friends",
  "Not being able to stop laughing with your friends",
  "Experiencing new cultures and celebrations",
  "Learning words from your friends language and them laughing at your accent",
  "A loved one giving you ointment for your wound",
  "Having inside jokes and unique words created with your friends",
  "Getting compliments for your scent",
  "Watching the days getting longer as summer approaches",
  "The privilege of watching the name mom, dad, grandpa, grandma pop up in your phone when they call",
  "The privilege of still being able to hear your mom's, dad's, grandpa's, grandma's voice",
  "Receiving a package from your home country with homemade foods and snacks you love while being abroad",
  "Someone telling they sincerely missed you after seeing them from a long time",
  "Getting flirted with",
  "Cooking for someone and they love the food",
  "When someone specifically approaches you for a topic because they know you have knowledge on that topic",
  "Getting 'did you arrive home safely?' texts and calls from someone that cares for you",
  "Unexpected sleepovers with friends",
  "Someone getting excited for your success",
  "Someone getting sad for something that happened to you",
  "Finding a person to talk about that one movie/book after dying to talk about it with someone",
  "Singing loudly songs with your friends in the street",
  "Getting tipsy with your friends",
  "The smell of suncream",
  "The way your hair looks underwater",
  "Summer evening walks",
  "Feeling the warmth of the sun on your skin",
  "Summer nights",
  "Taking a shower after a day at the beach",
  "The sound of the ocean",
  "Days when you feel pretty",
  "Those 'I love my life' moments",
  "When someone remembers the small things you like",
  "The first swim of the summer",
  "When the airplane takes off",
  "When the airplane lands",
  "Uncontrollable smiles",
  "Looking through old pictures",
  "Summer tan",
  "Sunrises/sunsets",
  "The way the light shines on water",
  "Telling a story that happened years ago and still smiling/laughing",
  "When little kids smile at you",
  "Listening to someone's heartbeat",
  "The sound of birds chirping in the morning",
  "When your pet rests their head on you",
  "Your favourite part of the song",
  "Handwritten letters",
  "When someone calls you their best friend",
  "Silence that isn't awkward",
  "When someone tells you that you smell nice",
  "Getting the bigger half of something",
  "When a show comes back after a long commercial break on the TV",
  "Buying something you saved money for",
  "The sound of heels clicking",
  "When you make a reference to a meme and someone gets it",
  "Not being able to finish a sentence because you're laughing so hard",
  "When you say 'bye' to a group and they all say it back",
  "Smiling in the middle of a kiss",
  "Songs that give you the chills",
  "Finally remembering the word that was on the tip of your tongue",
  "Walking barefoot on the beach",
  "Hearing people cheer for you",
  "Your friends teasing you",
  "Warm and dry towels after coming out from the shower",
  "Looking back and seeing how far you've come",
  "The first breath of air after coming up from underwater",
  "When someone drives you home and they wait until you unlock the door before driving away",
  "The moment before a kiss",
  "Good story tellers",
  "Listening to an old person's life story",
  "Finishing a book in one sitting",
  "When you stop and realise how perfect a moment is",
  "Waking up on a Christmas morning",
  "Movie nights",
  "Experiencing new culture when travelling",
  "Unexpected compliments",
  "Flirts",
  "Guys who smell good",
  "Photo Booth pictures",
  "Pens that make your handwriting better",
  "Crunchy grapes",
  "Sleeping with the windows open in summer",
  "Clean room",
  "Long weekends",
  "Turning a page when reading a book and realising that there's only a couple of words left",
  "Studying and realising that the next pages are only references and you are done",
  "Cookies straight out of the oven",
  "The excitement of your loved ones waiting for the food you are cooking",
  "When someone puts a blanket over you when you're sleeping",
  "The tininess of baby clothes and shoes",
  "Having time for yourself",
  "Being welcomed wholeheartedly into a group",
  "Kissing for the first time",
  "Singing along to the car radio",
  "The chubbiness of a baby's cheeks",
  "Night swimming",
  "When someone defends you in an argument",
  "Having someone to wait for you in the departures of the airport",
  "Pink promises",
  "The feeling after watching a good movie",
  "Making a baby laugh",
  "Movie marathons on rainy days",
  "Finally laughing after holding it in",
  "When someone values your opinions",
  "Pretty skies",
  "Cuddling",
  "Being called beautiful",
  "Hearing how people met",
  "Finding something you made when you were a kid",
  "Naps",
  "Warm and dry towels after coming out from the sea",
  "Having the privilege to love the cold and rainy weather",
  "Putting on the duvet after a hot summer",
  "Drinking cold water mid sleep",
  "Kisses on the forehead",
  "Watching the fireworks",
  "Making your parents proud",
  "Holding a baby in your arms",
  "The colour of people's eyes",
  "Coming home to the smell of good food",
  "Recreating your family's recipe and tasting exactly like it",
  "When people try to be quiet because they think you are asleep",
  "When someone defends you in an argument",
  "Kissing your crush for the first time",
  "Remembering the name of the song that has been stuck in your head",
  "Washing off the conditioner from your hair and them being soft",
  "Kisses on the neck",
  "Soft words from the one you like",
  "Someone complementing the weak parts of you",
  "Feeling easy to be loved",
  "Finding the person you were looking for in a crowd",
  "The glow of a candlelight",
  "Being interested in what is being taught in class",
  "Crawling back into a warm bed",
  "Getting your nails done and observing them for the next 24 hours with excitement",
  "Late night phone conversations",
  "Someone taking you home",
  "Goodbye hugs",
  "Goodbye kisses",
  "Feeling safe",
  "Getting tackled in a blanket that just got out of the dryer",
  "The feeling of making someone laugh after they were crying",
  "Having to hear a whole different perspective on something that you thought you would never change your mind",
  "Someone having the answer to something you were wondering for the longest time",
  "Having someone asking you questions on a topic they know you are a nerd about",
  "Someone pointing out something that you do that you never noticed that you do",
  "Convincing someone with your opinion/perspective",
  "Someone remembering foods that you (don't) like",
  "Having someone to wait for you in the airport",
  "To be privileged to have someone to miss",
];
